export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const GET_USER_ATTENDANCE_REQUEST = "GET_USER_ATTENDANCE_REQUEST";
export const GET_USER_ATTENDANCE_SUCCESS = "GET_USER_ATTENDANCE_SUCCESS";
export const GET_USER_ATTENDANCE_FAIL = "GET_USER_ATTENDANCE_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_DETAILS_REQUEST = "USER_UPDATE_DETAILS_REQUEST";
export const USER_UPDATE_DETAILS_SUCCESS = "USER_UPDATE_DETAILS_SUCCESS";
export const USER_UPDATE_DETAILS_FAIL = "USER_UPDATE_DETAILS_FAIL";


export const ALL_STUDENT_REQUEST = "ALL_STUDENT_REQUEST"
export const ALL_STUDENT_SUCCESS = "ALL_STUDENT_SUCCESS"
export const ALL_STUDENT_FAIL = "ALL_STUDENT_FAIL"

export const SINGLE_STUDENT_REQUEST = "SINGLE_STUDENT_REQUEST"
export const SINGLE_STUDENT_SUCCESS = "SINGLE_STUDENT_SUCCESS"
export const SINGLE_STUDENT_FAIL = "SINGLE_STUDENT_FAIL"
