export const GET_BRANCH_STUDENT_REQUEST = "GET_BRANCH_STUDENT_REQUEST";
export const GET_BRANCH_STUDENT_SUCCESS = "GET_BRANCH_STUDENT_SUCCESS";
export const GET_BRANCH_STUDENT_FAIL = "GET_BRANCH_STUDENT_FAIL";




